### ISSUE TITLE
在小米V10保活无效

### ISSUE THREAD

**Issue by boatt** [xuexiangjys/XPush#1]
在小米V10保活无效

**Comment by xuexiangjys** [comment]
首先，麻烦提issue前先阅读一下文档：[保活机制](https://github.com/xuexiangjys/XPush/wiki/%E4%BF%9D%E6%B4%BB%E6%9C%BA%E5%88%B6%E4%BD%BF%E7%94%A8)
其次，真是要提bug请按模板来
