### ISSUE TITLE
app杀死，也会走作者写的推送回调方法吗

### ISSUE THREAD

**Issue by TongShouJun** [xuexiangjys/XPush#10]
我还没有对接作者的demo。之前对接小米、华为通道推送，app被杀死，会收到通知栏推送消息，但是App里面的推送消息回调方法没有执行（基于IM聊天app,需要离线收到推送消息，唤醒app,链接自己socket,类似ios apns收到推送消息，可以短暂唤醒），所以想问作者此项目功能强大到可以解决我的问题的地步了吗

**Comment by xuexiangjys** [comment]
这个受限于系统限制，理论上是无法做到的，除非你可以定制rom，就像华为推送那样，把消息推送做成一个系统级的服务，这样这个服务就永远存活。一旦收到消息，这个服务就可以指定启动你的应用，然后静默执行对应的方法。
