### ISSUE TITLE
设置.setIsShow(false);  怎么还是会显示保活弹窗？

### ISSUE THREAD

**Issue by longwQaQ** [xuexiangjys/XPush#11]
三星手机

**Comment by xuexiangjys** [comment]
我用华为、小米和oppo都试过了,没有问题,暂时没三星手机,所有你还是自己调试吧

**Comment by yanpengqing** [comment]
亲测小米8 miui 11.0.3  基于安卓9.0 ， Genymotion模拟器8.0系统都会显示保活通知栏。
小米note 6.0.1不会显示。
这怎么解决？
