### ISSUE TITLE
感谢您的开源。

### ISSUE THREAD

**Issue by beiguancyc** [xuexiangjys/XPush#16]
使用了一段时间，应该说是目前使用最灵活，集成最简单的推送方案。
不知后续会不会添加魅族，Oppo，Vivo的厂商推送通道？

**Comment by xuexiangjys** [comment]
个人精力有限,维护的开源项目太多,这些小众的推送渠道建议还是自己尝试去集成吧,参照着源码集成起来也并不是很难
