### ISSUE TITLE
刚刚集成，并不能使用，极光推送不过来

### ISSUE THREAD

**Issue by weimingjue** [xuexiangjys/XPush#17]
**提Bug前需要做的事情**

**问题描述（必填）**
刚刚集成，并不能使用，极光推送不过来

**使用的XPush版本（必填）**
1.0.1

**如何重现（必填）**
重现的步骤:
集成代码：

build.gralde：
    //推送核心库
    api 'com.github.xuexiangjys.XPush:xpush-core:1.0.1'
    //推送保活库
    api 'com.github.xuexiangjys.XPush:keeplive:1.0.1'
    api 'com.github.xuexiangjys.XPush:xpush-jpush:1.0.1'
...
//                打包后mainfest里可以找到，并且原始极光可以收到
        manifestPlaceholders = [
                JPUSH_PKGNAME   : applicationId,
                XPush_JPush_1000: "com.xuexiang.xpush.jpush.JPushClient",
                JPUSH_APPKEY    : "...", //JPush 上注册的包名对应的 Appkey.
                JPUSH_CHANNEL   : "developer-default", //暂时填写默认值即可.
        ]

application：//主线程
        XPush.debug(BuildConfig.DEBUG);
        XPush.init(this, new JPushClient());
        XPush.register();
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
            //Android8.0静态广播注册失败解决方案二：修改发射器
            XPush.setIPushDispatcher(new Android26PushDispatcherImpl(CustomXPushReceiver.class));
        }

mainfest：
        
        <receiver android:name=".receiver.CustomXPushReceiver">
            <intent-filter>
                <action android:name="com.xuexiang.xpush.core.action.RECEIVE_CONNECT_STATUS_CHANGED" />
                <action android:name="com.xuexiang.xpush.core.action.RECEIVE_NOTIFICATION" />
                <action android:name="com.xuexiang.xpush.core.action.RECEIVE_NOTIFICATION_CLICK" />
                <action android:name="com.xuexiang.xpush.core.action.RECEIVE_MESSAGE" />
                <action android:name="com.xuexiang.xpush.core.action.RECEIVE_COMMAND_RESULT" />

                <category android:name="${applicationId}" />
            </intent-filter>
        </receiver>

混淆：debug模式没混淆，也添加了教程的忽略

**期望的效果**
去极光官网点击推送数据，完全收不到。我又手动集成了极光是可以搜到的

**截图**
如果方便的话，贴一下程序截图和代码片段以帮助解释您的问题。

**设备信息**
请填写一下你运行设备的信息，信息越全越有助于我理解问题
 - 设备名: 模拟器和小米都收不到
 - Android版本: 5.0、9.0
 - 设备型号 [e.g. ]
 - 系统版本（手机厂商定制rom）

**附加信息**
在此处添加任何有关该问题的任何其他说明。

**Comment by xuexiangjys** [comment]
首先,你写了一堆,我根本不知道你在说什么,表述非常混乱,重点什么都没写.
其次,我刚才试了一下,推送是正常的,考虑你肯定哪里配置有问题,建议仔细按照文档写,不要跳步骤.
最后,既然你已经自己集成了极光推送,那你就用原生集成方式好了,这种集成方式考虑可能不适合你.
以下是我刚刚试的截图:
![image](https://user-images.githubusercontent.com/15059629/80368655-a107de80-88bf-11ea-884f-94ae0b805dc4.png)
![image](https://user-images.githubusercontent.com/15059629/80368735-c563bb00-88bf-11ea-843c-6164c0fa57c9.png)
