### ISSUE TITLE
参照集成了oppo推送

### ISSUE THREAD

**Issue by Founder005** [xuexiangjys/XPush#24]
自定义的receiver继承了AbstractPushReceiver，但是onMessageReceived没有反应，想收到信息更新角标
![image](https://user-images.githubusercontent.com/15223210/93194457-b0a69780-f77a-11ea-825e-0b3438917127.png)
![image](https://user-images.githubusercontent.com/15223210/93194524-c451fe00-f77a-11ea-8206-1a0e52325749.png)

**Comment by xuexiangjys** [comment]
并不知道你在说什么

**Comment by Founder005** [comment]
解决了，这是oppo的原因，oppo推送不走receiver。
还有想问下，8.0上加上这句话XPush.registerPushReceiver(new CustomPushReceiver());后还需要  XPush.register();这一行代码么？

**Comment by xuexiangjys** [comment]
肯定需要啊
