### ISSUE TITLE
依赖下载不下来是怎么回事？

### ISSUE THREAD

**Issue by 993620475** [xuexiangjys/XPush#27]

**Comment by 993620475** [comment]
![image](https://user-images.githubusercontent.com/24223323/103112187-9f7cf900-468e-11eb-90cc-91d472f1e359.png)
一直卡住下载不下来

**Comment by xuexiangjys** [comment]
你这卡的地方都不在下载,依赖都没解析出来.建议换个网或者翻墙,或者使用阿里云maven库镜像
